// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGqT104iWykWHWpI_KO_T5v5M9M5ghk98',
    appId: '1:968254099718:web:43da3a191dd04c54d30e87',
    messagingSenderId: '968254099718',
    projectId: 'pochampally-sarees-8cd71',
    authDomain: 'pochampally-sarees-8cd71.firebaseapp.com',
    databaseURL: 'https://pochampally-sarees-8cd71-default-rtdb.firebaseio.com',
    storageBucket: 'pochampally-sarees-8cd71.appspot.com',
    measurementId: 'G-PTD339W44D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyaH1QNuQdI20-gJbxf7LN2-1wwac9ZlE',
    appId: '1:968254099718:android:fcfba51577178b2ed30e87',
    messagingSenderId: '968254099718',
    projectId: 'pochampally-sarees-8cd71',
    databaseURL: 'https://pochampally-sarees-8cd71-default-rtdb.firebaseio.com',
    storageBucket: 'pochampally-sarees-8cd71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5UZSsm66FC1zvHga9PZ6aWttX2LghP1c',
    appId: '1:968254099718:ios:b9a3c353f826abe5d30e87',
    messagingSenderId: '968254099718',
    projectId: 'pochampally-sarees-8cd71',
    databaseURL: 'https://pochampally-sarees-8cd71-default-rtdb.firebaseio.com',
    storageBucket: 'pochampally-sarees-8cd71.appspot.com',
    iosClientId: '968254099718-abt5hjhdkdd21147r6u8d8j6enli8ufk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pSarees',
  );
}
